### ISSUE TITLE
What is the tool to run better-enums in REPL mode in README.md?

### ISSUE THREAD

**Issue by SF-Zhou** [aantron/better-enums#105]
Hi, better-enums is a great job and I'd like it. I'd also like to know what this tool is in https://github.com/aantron/better-enums/blob/master/doc/image/sample.gif 😃

**Comment by aantron** [comment]
Thanks :) The output was inspired by Cling, but it is faked :) I wrote some script (in OCaml) to capture and play back keystrokes, with the added Cling-like output. I then used some GIF capture program (not sure now, I was on a different OS when I made that GIF).

**Comment by SF-Zhou** [comment]
Thanks~
