### ISSUE TITLE
Case insensitive string <-> enum support?

### ISSUE THREAD

**Issue by rcdailey** [aantron/better-enums#12]
I'm not sure if you support this, but for serialization purposes, it would be nice for case insensitivity when converting from string to enum.

Basically, a string `"FOO"` should map to an enumerator `Foo`.

**Comment by aantron** [comment]
I have this: http://aantron.github.io/better-enums/ApiReference.html#_from_string_nocase

Of course, as it is now, you have to choose to call it – the `>>` operator uses the case-sensitive function `_from_string`.

**Comment by aantron** [comment]
Presuming this is addressed, and closing. Let me know if I'm mistaken :)
