### ISSUE TITLE
HTML and placeholder variables in markdown files

### ISSUE THREAD

**Issue by UnrealQuester** [aantron/better-enums#2]
The markdown files in /tutorial and /doc contain html tags and placeholder variables such as ${prefix} that are used to generate the online project page. Sadly, the tags are fully visible and it breakes all links when viewed on github.
Example taken directly from the constexpr tutorial:

    #include <iostream>

    // The reason for this is explained below.
    #ifndef BETTER_ENUMS_CONSTEXPR_TO_STRING
    #define BETTER_ENUMS_CONSTEXPR_TO_STRING
    #endif

    <em>#include <enum.h></em>

    <em>ENUM</em>(<em>Channel</em>, <em>int</em>, <em>Red</em> = <em>1</em>, <em>Green</em> = <em>2</em>, <em>Blue</em> = <em>3</em>)

    <em>constexpr</em> Channel      channel = <em>Channel::_from_integral(2)</em>;
    <em>constexpr</em> int          value = <em>channel._to_integral()</em>;

    <em>constexpr</em> const char   *name = <em>channel._to_string()</em>;
    <em>constexpr</em> Channel      parsed = <em>Channel::_from_string("Red")</em>;

It would be nice if users could properly view the docs directly on the project page on github or use it as offline documentation. I am not sure if this is possible without breaking http://aantron.github.io/better-enums.

**Comment by aantron** [comment]
This is true. The primary purpose of the Markdown files is to be source for the examples and website, but it would be nice if they could also be fully usable when reading right on GitHub. I don't think this could be made to work without breaking the website build, however. I think the closest I could come is generating "nice" Markdown from source Markdown, but I am not sure I want to go there. There are some files that would be especially problematic, such as `index.md` (though I suppose I could partially take care of that by separating template replacement and HTML translation into phases).

Here are some alternatives. I'd like to hear what you think about them.

- For offline docs, it's possible to generate the web page and view it locally. The generator currently embeds a Google Analytics script. I have a todo item for making the generator not embed the tracking script by default, and embed it only when passed an option such as "`--web`". I would be the only person that ever used this option. I would also commit the mistune module to the repository – the generator depends on it.
- I have a todo item for pre-generating the offline version and making it downloadable from the web site as a zip file. I could also commit it unpacked to the repository. Hopefully it would be viewable on GitHub. I would hide the Markdown in `doc/src`.
- I could simply put a `README` file in `doc/` telling people not to read the Markdown and redirecting them to the website, if they want working links or fully legible text and code :)

**Comment by UnrealQuester** [comment]
Being able to generate the documentation myself would be enough for me. Option 1 looks like a good compromise.

Thank you for taking your time to consider this issue.

**Comment by aantron** [comment]
Give this a try – as the commit message says, you should now be able to get the docs generated by typing `make` in `doc/`, without having to install anything.

**Comment by UnrealQuester** [comment]
Works like a charm!
