### ISSUE TITLE
Declare inside class

### ISSUE THREAD

**Issue by fnc12** [aantron/better-enums#20]
I want to make a role field for a user. So I try to compile this code:
```
struct User{
    BETTER_ENUM(Role, int,
                user,
                driver)
};
```

and it tells me `Missing '}' at end of definition of 'User'` at the first line and `Extraneous closing brace ('}')` at the last line. Compiling using Xcode 7.3.1. The issue is how to create enum enclosed inside a class?

**Comment by aantron** [comment]
Hi, this isn't possible in current versions, unfortunately. I believe this should work as a workaround, however:

```cpp
BETTER_ENUM(some_ugly_prefix_Role, int, user, driver)

struct User {
    using Role = some_ugly_prefix_Role;
    // ...
};
```

**Comment by fnc12** [comment]
@aantron thanks
