### ISSUE TITLE
Usage to handle measurement units with '/' character

### ISSUE THREAD

**Issue by escherstair** [aantron/better-enums#32]
I see Better Enums is a nice project and I'd like using it to define a set of measurement units.
The problem is that some of them (m/s, km/h, ...) contain a '/' character in their string representation.

Is there a way to handle this in Better Enum?

**Comment by aantron** [comment]
Am I correct to assume that you want to include the `/` in the identifier, i.e. something like

```cpp
BETTER_ENUM(Unit, int, m/s, km/h);
```

If so, I don't think it's doable. Even if it was definable (I don't think it is), you would have trouble using such constants elsewhere in your code, as `m/s` doesn't parse as a single identifier. It parses as two identifiers and the operator `/`.

The nearest thing I can recommend is replacing `/` by `_`: `m_s`, `km_h`. It's uglier, but it should work.

There are probably some kind of expression [template] techniques you can abuse to get expressions like `m/s` to have the desired meaning and to carry out dimensional analysis during compilation. But these techniques are orthogonal to Better Enums. You could use the library to define

```cpp
BETTER_ENUM(Time, int, s, h);
BETTER_ENUM(Distance, int, m, km);
```

and then use those in your dimensional analysis scheme.

**Comment by escherstair** [comment]
I need the `/` in the string representing the identifier (output from `_to_string()`).
I can have a different character in the identifier itself, but I think this cannot be done with this library.
For other units I need other "strange" character, like `°`, so I thin I should investigate a different approach.

**Comment by aantron** [comment]
It may be possible to somehow get Better Enums to output `/` even though it does not appear in the identifier, but I guess this would be quite hacky and probably not suitable for general usage. So, I wouldn't put it in `master` or the public/main version.

I hope you found a good solution to this. I'm closing the issue. Feel free to comment/reopen if needed.
