### ISSUE TITLE
Visual Studio Intellisense

### ISSUE THREAD

**Issue by MattiasEppler** [aantron/better-enums#46]
Hi.

Visual Studio 2017:
If I hover a instance of a normal enum type the name and the value are displayed.
If I hover a instance of a better enum type only the value is displayed.

Is it possible to display also the name on better enums?

**Comment by aantron** [comment]
I would hope so. At least, it should be possible to display something like `YourEnum::_enumerated` for the type. It's slightly ugly, but that is the actual internal type of the instances.

I'm not sure what is confusing Intellisense (actually I don't really know how it works, exactly).

**Comment by aantron** [comment]
(But if I had to speculate, I would say it's all the macros: `_enumerated` is inside a macro expansion, but it also has macro usage inside its own definition, inside that expansion. I don't know to what extent Intellisense can handle that).

**Comment by aantron** [comment]
Closing, as it needs more info to address.
