### ISSUE TITLE
Warning: use of old-style cast

### ISSUE THREAD

**Issue by ftab** [aantron/better-enums#48]
In Qt Creator, with the Clang code model selected (help -> about plugins -> C++), I see the following warning:

Semantic Issue | -Wold-style-cast
-- | --
23:5: warning: use of old-style cast
[enum.h:1089](https://github.com/aantron/better-enums/blob/2fad3f60eea97cf3b75339a1562ab13d5e0cc4f7/enum.h#L1089):21: note: expanded from macro 'BETTER_ENUM'
[enum.h:679](https://github.com/aantron/better-enums/blob/2fad3f60eea97cf3b75339a1562ab13d5e0cc4f7/enum.h#L679):23: note: expanded from macro 'BETTER_ENUMS_TYPE'
[enum.h:500](https://github.com/aantron/better-enums/blob/2fad3f60eea97cf3b75339a1562ab13d5e0cc4f7/enum.h#L500):13: note: expanded from macro 'BETTER_ENUMS_EAT_ASSIGN'
:0:0: note: (skipping 4 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
[enum.h:114](https://github.com/aantron/better-enums/blob/2fad3f60eea97cf3b75339a1562ab13d5e0cc4f7/enum.h#L114):28: note: expanded from macro 'BETTER_ENUMS_ID'
enum.h:114:28: note: expanded from macro 'BETTER_ENUMS_ID'
enum.h:114:28: note: expanded from macro 'BETTER_ENUMS_ID'

(If I have the default code model selected, I get warnings whenever I use BETTER_ENUM(), and code completion/coloring doesn't work for those enums, so I kinda have to use the clang code model)

**Comment by aantron** [comment]
Presumably fixed in #74 (thanks @FelipeLema, @MartinDelille).
