### ISSUE TITLE
No Compiler warning for missing case in Switch statement

### ISSUE THREAD

**Issue by Ar5ham** [aantron/better-enums#49]
Copy pasting the [SafeSwitch](http://aantron.github.io/better-enums/tutorial/SafeSwitch.html) example to project created via Visual Studio 2017 and compiling the project, no warning is being produced by the compiler. 

Compiler Version:
```
# From Developer Command Prompt for VS 2017
>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25019
````

Sample project:
[BetterEnumTest.zip](https://github.com/aantron/better-enums/files/1312860/BetterEnumTest.zip)

**Comment by aantron** [comment]
That's not good!

I'm not immediately ready to reproduce this, but thanks for including the project. I'll have to look at it after some delay :/

**Comment by ar5ham** [comment]
That is fine.  Please let me know if you need any more info.

**Comment by JaapAap** [comment]
For some reason, the warning is off by default, see [here](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4062). You need to add something like 
#pragma warning(1 : 4062)  to enable it.

**Comment by aantron** [comment]
It seems that this can only be done by the user, so the code proper of Better Enums doesn't need to be modified.

However, we should probably document enabling this warning, perhaps by adding a short sentence and the link given by @JaapAap, to the tutorial and/or reference.

**Comment by ikku100** [comment]
Yes, please document this issue. I spent 15 minutes trying to get this to fail, then I was about to complain about it and apparently it's a known issue! Imho either change the introduction page to mention that it needs enabling for all those people who are sadly on Visual Studio compilers, or remove the mentioning of the feature. Same for the tutorial page on the switch.

**Comment by Ar5ham** [comment]
Enabling that feature is not always an option either, just FYI. Our project uses shared Libs and public headers and when I enabled the feature I also got warning related to Libs and headers that was not ours to begin with. I have picked up a work item to go take a look at how difficult it would be to fix all of them but I suspect it will be a time consuming effort.

**Comment by aantron** [comment]
Thanks for pinging. I updated the [README](https://github.com/aantron/better-enums#limitations) and the [`switch` tutorial page](http://aantron.github.io/better-enums/tutorial/SafeSwitch.html) with notes about enabling warning C4062 on msvc. I hope that's enough, please let me know/PR if more warnings are needed.

**Comment by ikku100** [comment]
That's great, thanks Aantron. It's indeed enough.
