### ISSUE TITLE
Compiler limit for expanded limit (only 127 allowed)

### ISSUE THREAD

**Issue by Zyres** [aantron/better-enums#57]
I tried the to expand the item limit to fit my needs.
I have an enum with ~1400 list members. Using MSVC I triggered C1112 (compiler limit:'1400' too many macro arguments, only '127' allowed.

**Comment by aantron** [comment]
Preprocessing or compiling using clang-cl may also work.

Closing this issue, as it's not a problem with Better Enums, and I don't think we can work around it in Better Enums.

**Comment by Roman-Bober** [comment]
Any updates on this bug?
got also in VS2015

fatal error C1112: compiler limit
after running and using generated enum_macros.h:

make_macros.py"  256 64 > "C:\work\GitLab\imageinjecttools\src\ImageInjectLib\enum_macros.h"

**Comment by aantron** [comment]
AFAIK this is a limitation in MSVC. If you are able to use a newer version, perhaps you can try to see if they have increased the limit.

**Comment by xiayip** [comment]
I add an MSVC compile flag to reslove this problem:
```
    if (MSVC)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /Zc:preprocessor")
    endif ()
```
Here is [more info](https://learn.microsoft.com/en-us/cpp/cpp/compiler-limits?view=msvc-170) about MSVC compile limit.
