### ISSUE TITLE
There are illegal identifiers: underscore followed by uppercase letter is reserved.

### ISSUE THREAD

**Issue by FelixDombek** [aantron/better-enums#61]
better-enums uses some identifiers which are not allowed according to the C++ standard. Identifiers beginning with an underscore followed by an uppercase letter are reserved in any namespace ([ref](https://en.cppreference.com/w/cpp/language/identifiers)). better-enums uses three of those:

 - `_Iterable`
 - `_PutNamesInThisScopeAlso`
 - `_EnumClassForSwitchStatements`

What makes it worse is that these identifiers are not only in library headers, but are inserted into all users' source files via macros. Therefore, code quality checkers flag all sources using better-enums as violating standards.

**Comment by aantron** [comment]
Fixed by @FelixDombek in #62. Thanks!
