### ISSUE TITLE
forward declaration BETTER_ENUM 

### ISSUE THREAD

**Issue by jafar75** [aantron/better-enums#83]
Is it possible to declare BETTER_ENUM(enum_name, type) without initializing. and later add values to it?   
I mean similar with enum class in c++11.

**Comment by aantron** [comment]
You may be able to forward-declare the enum using just its class name, so if you have

```
BETTER_ENUM(Color, int, 1, 2, 3)
```

the forward declaration should be

```
class Color;
```
