### ISSUE TITLE
Better clarify magic_enum's requirements in README

### ISSUE THREAD

**Issue by alexeyr** [aantron/better-enums#88]
Currently the README says

> Note: consider magic_enum (if using GCC, requires at least GCC 9.0).

It would be nice to: 
1. note it requires C++17; 
2. specify required versions for other compilers; 
3. (maybe) link directly to https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md.

**Comment by aantron** [comment]
Thanks. I've edited the README.
