### ISSUE TITLE
Visual Studio 2015 constexpr status

### ISSUE THREAD

**Issue by aantron** [aantron/better-enums#9]
Visual Studio 2015 added support for `constexpr`, but the implementation seems too buggy to get it working with Better Enums without a bunch of workarounds. Progress is in the branch [`vs2015-constexpr`](https://github.com/aantron/better-enums/tree/vs2015-constexpr). Internal compiler errors can be seen [here](https://ci.appveyor.com/project/aantron/better-enums/build/37/job/0cp67wvj40jelefh) – search for "error" in the log.

**Comment by rcdailey** [comment]
They STILL don't have this right in 2015??? I've lost all patience for visual studio.

**Comment by aantron** [comment]
In some days or weeks I will go through the remaining problems Better Enums has with VS2015 `constexpr` and try to resolve as many as possible, resulting in some combination of bug reports to Microsoft and either a new release, or advancing the `vs2015` branch.

**Comment by rcdailey** [comment]
I think it's great that you can work around the problems. My frustration however is that MSVC isn't keeping up with OSS toolchains like Clang and GCC, when MSVC has the backing of a multi-billion dollar corporation as well as Herb Sutter to lead it in the right direction. Logically it just doesn't make sense. But then again, this has always been MSVC's legacy.

**Comment by mbevin** [comment]
Note - I've been using the latest update 2, and it stiiill has problems like that it likes to crash with internal compiler errors if you do anything like for example try to use the constexpr versions of the stringizing stuff (i.e. BETTER_ENUMS__CXX11_FULL_CONSTEXPR_TRIM_STRINGS_ARRAYS) (which I've been discovering as was using in some of my own code).

**Comment by aantron** [comment]
Ah, good to know. Thanks. I was planning to look at this again in the coming weeks. Is compilation on MSVC working without `constexpr` `to_string` now, though?

**Comment by mbevin** [comment]
yeah betterenums is working fine for me on MSVC (using i think the totally non constexpr variant) - it was actually only when i was using that code in some of my own stuff, and had directly used the full_constexpr versions of the macros, that i hit msvc compiler internal errors ...

**Comment by mbevin** [comment]
tho actually ... one issue I do have with VS, is it doesn't seem to allow having #ifdefs inside a ENUM(...), i.e. if one wants to disable certain values from being in the enum according to some define(s). Don't know if this is a known issue?

**Comment by mbevin** [comment]
(whereas this works fine on like clang)

**Comment by torbjoernk** [comment]
One thing one might need to consider is, that `switch` inside `constexpr` functions is not supported in VS2015 Update 3 yet, i.e. ["Extended constexpr (N3652)"](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3652.html). Thus, the ["mapping"](http://aantron.github.io/better-enums/tutorial/Maps.html) working draft feature is not supported by MSVC.

**Comment by Zerophase** [comment]
If I define `BETTER_ENUMS_HAVE_CONSTEXPR` Everything seems to compile successfully with VS2017.

**Comment by michaelernst** [comment]
It works with for me with VS2017 as well. Could you add a check if _MSC_VER is greater xxx and define BETTER_ENUMS_HAVE_CONSTEXPR?

**Comment by aantron** [comment]
VS2017 `constexpr` detection was added in #47. Would you mind trying the `enum.h` directly from the repo, if you haven't already?

**Comment by michaelernst** [comment]
Directly from the repository does work. I think we downloaded a release version, maybe you should update the current release.

Best,
Michael

**Comment by aantron** [comment]
Yes, I'll make a new one shortly, and update the link.
