### ISSUE TITLE
Plan for next release e.g. 0.11.3? 

### ISSUE THREAD

**Issue by saimusdev** [aantron/better-enums#90]
Hi, 

is there any plans for a new release from master that includes latest fixes, like the old-style cast stuff?

Thanks!

**Comment by aantron** [comment]
There weren't, but now I will plan it for next week.

**Comment by aantron** [comment]
I updated the docs and tagged 0.11.3. The changelog is [here](https://github.com/aantron/better-enums/releases/tag/0.11.3). Thanks for the prod!
