### ISSUE TITLE
VS limit of extending better enums beyon 127

### ISSUE THREAD

**Issue by Roman-Bober** [aantron/better-enums#93]
Any updates on this bug?
got also in VS2015

fatal error C1112: compiler limit
after running and using generated enum_macros.h:

make_macros.py"  256 64 > "C:\work\GitLab\imageinjecttools\src\ImageInjectLib\enum_macros.h"

**Comment by aantron** [comment]
Closing in favor of https://github.com/aantron/better-enums/issues/57#issuecomment-725241414. It's an MSVC issue AFAIK.
